# Generated by Django 4.2.23 on 2025-08-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solo_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agility',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_class',
            field=models.CharField(default='Hunter', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(default='E-Rank Hunter', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perception',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vitality',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('level_up', 'Level Up'), ('job_change', 'Job Change'), ('quest_reminder', 'Quest Reminder'), ('achievement', 'Achievement'), ('warning', 'Warning')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Epic', 'Epic')], max_length=10)),
                ('xp_reward', models.IntegerField()),
                ('quest_type', models.CharField(choices=[('daily', 'Daily Quest'), ('weekly', 'Weekly Quest'), ('custom', 'Custom Quest')], default='custom', max_length=10)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('target_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
